version: '3.4'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=builder
    volumes:
      - /mysql:/var/lib/mysql
    restart: always       
    networks:
      - rest
  sb-client:
    image: sb-client-rest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - rest
    depends_on:
      - db
networks:
  rest:
    driver: bridge
